"""I still don't know what I'm doing

Revision ID: 4ee1395f05ec
Revises: a0dc1c88e218
Create Date: 2022-01-28 00:16:10.490221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ee1395f05ec'
down_revision = 'a0dc1c88e218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('eventid', postgresql.UUID(), nullable=False))
    op.drop_constraint('responses_event_fkey', 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'events', ['eventid'], ['id'])
    op.drop_column('responses', 'event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('event', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key('responses_event_fkey', 'responses', 'events', ['event'], ['id'])
    op.drop_column('responses', 'eventid')
    # ### end Alembic commands ###
