"""Add updated time for responses

Revision ID: 859b0a485f80
Revises: 4ee1395f05ec
Create Date: 2022-01-28 09:28:25.222916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859b0a485f80'
down_revision = '4ee1395f05ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'updated')
    # ### end Alembic commands ###
